name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1

      - name: Deploy gateway
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: eb20014f-9e0a-45fd-822b-e079da851716
          heroku_app_name: rsoi-lab2-gateway-mirzoyan
          heroku_email: sergey.mirzoyan@bk.ru
          usedocker: true
          docker_build_args: SERVICE
        env:
          SERVICE: gateway

      - name: Deploy library
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: eb20014f-9e0a-45fd-822b-e079da851716
          heroku_app_name: rsoi-2-library-mirzoyan
          heroku_email: sergey.mirzoyan@bk.ru
          usedocker: true
          docker_build_args: SERVICE
        env:
          SERVICE: library

      - name: Deploy reservation
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: eb20014f-9e0a-45fd-822b-e079da851716
          heroku_app_name: rsoi-2-reserve-mirzoyan
          heroku_email: sergey.mirzoyan@bk.ru
          usedocker: true
          docker_build_args: SERVICE
        env:
          SERVICE: reservation

      - name: Deploy rating
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: eb20014f-9e0a-45fd-822b-e079da851716
          heroku_app_name: rsoi-2-rating-mirzoyan
          heroku_email: sergey.mirzoyan@bk.ru
          usedocker: true
          docker_build_args: SERVICE
        env:
          SERVICE: rating

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/[rsoi] postman_collection.json
          environment: v4/postman/[rsoi][heroku] postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'
          envVar: '[{ "key":"serviceName", "value":"rsoi-2-rating-mirzoyan" }, { "key":"herokuApiToken", "value":"eb20014f-9e0a-45fd-822b-e079da851716" }]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true
